for: for.c
	gcc for.c -o for.out
	gcc -O0 for.c -S

dowhile: dowhile.c
	gcc dowhile.c -o dowhile.out
	gcc -O0 dowhile.c -S

while: while.c
	gcc while.c -o while.out
	gcc -O0 while.c -S

continue: continue.c
	gcc continue.c -o continue.out
	gcc -O0 continue.c -S

break: break.c
	gcc break.c -o break.out
	gcc -O0 break.c -S

clean:
	rm -rf *.out *.s